[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chb_chess = {git = "https://github.com/CHB2025/chess.git", tag = "v0.1.1"}
leptos = "0.2.5"
web-sys = { version = "0.3.61", features = ["HtmlDivElement"] }

