[workspace]

members = [
    "frontend",
    "server",
    "api",
]

[[workspace.metadata.leptos]]
name = "web_chess"
bin-package = "server"
lib-package = "frontend"
lib-features = ["hydrate"]
assets-dir = "assets"
style-file = "styles/style.scss"
